-- Create tables in snake_case as per user rules

-- 1. Secciones
CREATE TABLE secciones (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    nombre TEXT NOT NULL UNIQUE, -- ej. '10-1'
    nivel INTEGER NOT NULL CHECK (nivel IN (10, 11)) -- 10 para Décimo, 11 para Undécimo
);

-- Ejemplo de inserción de secciones
INSERT INTO secciones (nombre, nivel) VALUES 
('10-1', 10), ('10-2', 10), ('10-3', 10),
('11-1', 11), ('11-2', 11), ('11-3', 11)
ON CONFLICT (nombre) DO NOTHING;


-- 2. Estados de Asistencia (The 12 variations)
CREATE TABLE estados_asistencia (
    id INTEGER PRIMARY KEY,
    nombre TEXT NOT NULL,
    peso_ausencia NUMERIC NOT NULL DEFAULT 0, -- Weight for dashboard calculations
    es_justificada BOOLEAN DEFAULT FALSE
);

INSERT INTO estados_asistencia (id, nombre, peso_ausencia, es_justificada) VALUES
(1, 'Presencia total', 0, FALSE),
(2, 'Ausencia total (4 lecciones)', 4, FALSE),
(3, 'Ausencia 1° lección', 1, FALSE),
(4, 'Ausencia 1° y 2° lección', 2, FALSE),
(5, 'Ausencia 1°, 2° y 3° lección', 3, FALSE),
(6, 'Tardía 1° lección', 0.5, FALSE),
(7, 'Tardía 3° lección', 0.5, FALSE),
(8, 'Ausencia 1° + Tardía 2°', 1.5, FALSE),
(9, 'Ausencia 1° y 2° + Tardía 3°', 2.5, FALSE),
(10, 'Ausencia 1°, 2° y 3° + Tardía 4°', 3.5, FALSE),
(11, 'Escapes (2°, 3° o 4° lección)', 1, FALSE),
(12, 'Justificación', 0, TRUE);

-- 3. Estudiantes
CREATE TABLE estudiantes (
    cedula TEXT PRIMARY KEY,
    nombre TEXT NOT NULL,
    apellidos TEXT NOT NULL,
    email TEXT, -- Generated by trigger
    seccion_id UUID REFERENCES secciones(id) ON DELETE CASCADE
);

-- Trigger for student logic: UPPERCASE names and [cedula]@est.mep.go.cr
CREATE OR REPLACE FUNCTION process_student_data()
RETURNS TRIGGER AS $$
BEGIN
    NEW.nombre := UPPER(NEW.nombre);
    NEW.apellidos := UPPER(NEW.apellidos);
    NEW.email := NEW.cedula || '@est.mep.go.cr';
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_process_student
BEFORE INSERT OR UPDATE OF cedula, nombre, apellidos ON estudiantes
FOR EACH ROW
EXECUTE FUNCTION process_student_data();


-- 4. Registro de Asistencia
CREATE TABLE control_asistencia (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    estudiante_id TEXT REFERENCES estudiantes(cedula) ON DELETE CASCADE,
    seccion_id UUID REFERENCES secciones(id) ON DELETE CASCADE,
    fecha DATE NOT NULL,
    estado_id INTEGER REFERENCES estados_asistencia(id) DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(estudiante_id, fecha)
);

-- RLS (Row Level Security) - Basic setup (User should adjust as needed)
ALTER TABLE secciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE estados_asistencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE estudiantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE control_asistencia ENABLE ROW LEVEL SECURITY;

-- Clean up existing policies to avoid conflicts
DROP POLICY IF EXISTS "Public read sections" ON secciones;
DROP POLICY IF EXISTS "Public read states" ON estados_asistencia;
DROP POLICY IF EXISTS "Public read students" ON estudiantes;
DROP POLICY IF EXISTS "Public read attendance" ON control_asistencia;
DROP POLICY IF EXISTS "Public full access students" ON estudiantes;
DROP POLICY IF EXISTS "Public full access attendance" ON control_asistencia;
DROP POLICY IF EXISTS "Authenticated update attendance" ON control_asistencia;


-- Select policies (Public read/write for development/anon access)
CREATE POLICY "Public read sections" ON secciones FOR SELECT USING (true);
CREATE POLICY "Public read states" ON estados_asistencia FOR SELECT USING (true);
CREATE POLICY "Public full access students" ON estudiantes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access attendance" ON control_asistencia FOR ALL USING (true) WITH CHECK (true);


-- 5. Configuración Diaria (Lecciones por día)
CREATE TABLE configuracion_diaria (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    seccion_id UUID REFERENCES secciones(id) ON DELETE CASCADE,
    fecha DATE NOT NULL,
    lecciones_totales INTEGER NOT NULL CHECK (lecciones_totales BETWEEN 1 AND 4),
    UNIQUE(seccion_id, fecha)
);

ALTER TABLE configuracion_diaria ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public full access config" ON configuracion_diaria;
CREATE POLICY "Public full access config" ON configuracion_diaria FOR ALL USING (true) WITH CHECK (true);

-- 6. Trabajo Cotidiano
CREATE TABLE trabajos_cotidianos (
    id SERIAL PRIMARY KEY,
    nombre TEXT NOT NULL,
    seccion_id UUID REFERENCES secciones(id) ON DELETE CASCADE,
    fecha DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE indicadores (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    trabajo_id INT REFERENCES trabajos_cotidianos(id) ON DELETE CASCADE,
    titulo TEXT NOT NULL,
    orden INT NOT NULL,
    desc_0 TEXT, -- No evidencia
    desc_1 TEXT, -- No logrado
    desc_2 TEXT, -- En proceso
    desc_3 TEXT  -- Logrado
);

CREATE TABLE evaluaciones_cotidiano (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    estudiante_id TEXT REFERENCES estudiantes(cedula) ON DELETE CASCADE,
    indicador_id UUID REFERENCES indicadores(id) ON DELETE CASCADE,
    puntaje INT CHECK (puntaje >= 0 AND puntaje <= 3),
    UNIQUE(estudiante_id, indicador_id)
);

-- RLS for Trabajo Cotidiano
ALTER TABLE trabajos_cotidianos ENABLE ROW LEVEL SECURITY;
ALTER TABLE indicadores ENABLE ROW LEVEL SECURITY;
ALTER TABLE evaluaciones_cotidiano ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public full access TC" ON trabajos_cotidianos;
DROP POLICY IF EXISTS "Public full access indicadores" ON indicadores;
DROP POLICY IF EXISTS "Public full access evaluaciones" ON evaluaciones_cotidiano;

CREATE POLICY "Public full access TC" ON trabajos_cotidianos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access indicadores" ON indicadores FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access evaluaciones" ON evaluaciones_cotidiano FOR ALL USING (true) WITH CHECK (true);
-- 7. Tareas
CREATE TABLE tareas (
    id SERIAL PRIMARY KEY,
    nombre TEXT NOT NULL,
    seccion_id UUID REFERENCES secciones(id) ON DELETE CASCADE,
    porcentaje FLOAT NOT NULL DEFAULT 5.0,
    puntos_totales INT NOT NULL DEFAULT 10,
    fecha DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE indicadores_tarea (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tarea_id INT REFERENCES tareas(id) ON DELETE CASCADE,
    titulo TEXT NOT NULL,
    orden INT NOT NULL,
    desc_0 TEXT,
    desc_1 TEXT,
    desc_2 TEXT,
    desc_3 TEXT
);

CREATE TABLE evaluaciones_tarea (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    estudiante_id TEXT REFERENCES estudiantes(cedula) ON DELETE CASCADE,
    indicador_id UUID REFERENCES indicadores_tarea(id) ON DELETE CASCADE,
    puntaje INT CHECK (puntaje >= 0 AND puntaje <= 3),
    UNIQUE(estudiante_id, indicador_id)
);

-- RLS for Tareas
ALTER TABLE tareas ENABLE ROW LEVEL SECURITY;
ALTER TABLE indicadores_tarea ENABLE ROW LEVEL SECURITY;
ALTER TABLE evaluaciones_tarea ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public full access tareas" ON tareas;
DROP POLICY IF EXISTS "Public full access ind_tareas" ON indicadores_tarea;
DROP POLICY IF EXISTS "Public full access eval_tareas" ON evaluaciones_tarea;

CREATE POLICY "Public full access tareas" ON tareas FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access ind_tareas" ON indicadores_tarea FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access eval_tareas" ON evaluaciones_tarea FOR ALL USING (true) WITH CHECK (true);

-- 8. Exámenes
CREATE TABLE examenes (
    id SERIAL PRIMARY KEY,
    nombre TEXT NOT NULL,
    seccion_id UUID REFERENCES secciones(id) ON DELETE CASCADE,
    porcentaje FLOAT NOT NULL DEFAULT 25.0,
    puntos_totales INT NOT NULL DEFAULT 30,
    fecha DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE indicadores_examen (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    examen_id INT REFERENCES examenes(id) ON DELETE CASCADE,
    titulo TEXT NOT NULL,
    orden INT NOT NULL,
    desc_0 TEXT,
    desc_1 TEXT,
    desc_2 TEXT,
    desc_3 TEXT
);

CREATE TABLE evaluaciones_examen (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    estudiante_id TEXT REFERENCES estudiantes(cedula) ON DELETE CASCADE,
    indicador_id UUID REFERENCES indicadores_examen(id) ON DELETE CASCADE,
    puntaje INT CHECK (puntaje >= 0 AND puntaje <= 3),
    UNIQUE(estudiante_id, indicador_id)
);

-- RLS for Exámenes
ALTER TABLE examenes ENABLE ROW LEVEL SECURITY;
ALTER TABLE indicadores_examen ENABLE ROW LEVEL SECURITY;
ALTER TABLE evaluaciones_examen ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public full access examenes" ON examenes;
DROP POLICY IF EXISTS "Public full access ind_examenes" ON indicadores_examen;
DROP POLICY IF EXISTS "Public full access eval_examenes" ON evaluaciones_examen;

CREATE POLICY "Public full access examenes" ON examenes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access ind_examenes" ON indicadores_examen FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access eval_examenes" ON evaluaciones_examen FOR ALL USING (true) WITH CHECK (true);
